### ISSUE TITLE
It looks like there's something wrong with this function “strlen(unsigned char*)”

### ISSUE THREAD

**Issue by 0xdaidai** [monkeyDemon/Blockchain-programming-exercises#2]
When I do my homework, I have this problem: two identical messages produce different hash codes. Through debugging, I found that their bufs have different length problems, but they are basically the same. Personal guess is because of the problem with the function“strlen”.I hope to get help!

**Comment by Weird733** [comment]
@0xdaidai you need transform the chinese to utf8 uniform when you use chinese

**Comment by 0xdaidai** [comment]
> @0xdaidai you need transform the chinese to utf8 uniform when you use chinese

Sorry, thanks for the reminder!
